config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'users/new'
  get 'users/create'
  get 'orders', to: 'orders#new'
  get 'orders/new', to: 'orders#create'
  resources :orders, only: [:new, :create]
  resources :users, only: [:new, :create]
  root to: 'users#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
  end

  def create
    @api ||= Moip.new.call
    @order = @api.order.create(order_json)
    @payment = @api.payment.create(@order.id, payment_json)
  end

  private

  def order_json
    user = User.last
    uniqueId = SecureRandom.hex
    {
      ownId: uniqueId,
      amount: {
        currency: 'BRL',
        subtotals: {
          shipping: 0
        }
      },
      items: [
        {
          product: 'recarga',
          category: 'OTHER_CATEGORIES',
          quantity: 1,
          price: params[:order][:amout].to_i*100,
        }
      ],
        customer: {
        ownId: user.ownid,
        fullname: user.fullname,
        email: user.email,
        taxDocument: {
          type: 'CPF',
          number: user.cpf,
        },
        phone: {
          countryCode: '55',
          areaCode: user.phoneArea,
          number: user.phoneNumber,
        },
        shippingAddress: {
          street: 'Avenida 23 de Maio',
          streetNumber: 654,
          city: 'Sao Paulo',
          district: 'Centro',
          state: 'SP',
          country: 'BRA',
          zipCode: '01244500',
        }
      }
    }
  end

  def payment_json
    {
      installment_count: 1,
      funding_instrument: {
        credit_card: {
          id: @order.customer.funding_instrument.credit_card.id,
          brand: @order.customer.funding_instrument.credit_card.brand,
          first6: @order.customer.funding_instrument.credit_card.first6,
          last4: @order.customer.funding_instrument.credit_card.last4,
          store: @order.customer.funding_instrument.credit_card.store,
          cvc: 123,
        },
        method: 'CREDIT_CARD',
      }
    }
  end
end

# @order.customer.funding_instrument

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
  	@api = Moip.new.call
    @uniqueId = SecureRandom.hex
    customer = @api.customer.create(user_json)
    @moipid = customer.id

    card = @api.customer.add_credit_card(@moipid, card_json)
    @ccid = card.credit_card.id

    User.create(
      fullname: params[:user][:fullname],
      email: params[:user][:email],
      ownid: @uniqueId,
      phoneArea: params[:user][:areaCode],
      cpf: params[:user][:cpf],
      phoneNumber: params[:user][:phoneNumber],
      moipid: @moipid,
    )
  end

  private

  def user_json
  {
    ownId: @uniqueId,
      email: params[:user][:email],
      fullname: params[:user][:fullname],
      birthDate: params[:user][:birthDate],
      taxDocument: {
            type: "CPF",
            number: params[:user][:cpf],
        },
      phone: {
        countryCode: "55",
        areaCode: params[:user][:areaCode],
        number: params[:user][:phoneNumber],
      },
    }
  end

  def card_json
    {
       method: "CREDIT_CARD",
       creditCard: {
         expirationMonth: params[:cc][:expirationMonth],
         expirationYear: params[:cc][:expirationYear],
         number: params[:cc][:number],
         cvc: params[:cc][:cvc],
         holder: {
           fullname: params[:user][:fullname],
           birthdate: params[:user][:birthDate],
           taxDocument: {
             type: "CPF",
             number: params[:user][:cpf],
           },
           phone: {
             countryCode: "55",
             areaCode: params[:user][:areaCode],
             number: params[:user][:phoneNumber],
           },
         },
       },
     }
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Moipapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/create.html.erb
<h1>Pedido enviado</h1>
<h3><%= @order.customer.funding_instrument %> </h3><br><br>
<h3> <%= @payment %> </h3>

app/views/orders/new.html.erb
<%= form_tag orders_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>


    <h3>
      <%= tag.label 'Valor' %><br>
      <%= tag.input type: 'text', name: 'order[amout]',
          value: '30', size: 8, id: :amount %>
    </h3>

    <p>
      <%= tag.button type: :submit do %>
        Confirma
      <% end %>
    </p>
  </article>

<% end %>

app/views/users/create.html.erb
<p>Usuario Criado</p>
<%= @moipid %><br>
<p>Cartão Vinculado</p>
<%= @ccid %><br>
<%= link_to '<button type="button">Recarregar</button>'.html_safe, "/orders" %>

app/views/users/new.html.erb
<%= form_tag users_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>

    <h3>
      <%= tag.label 'Nome Completo do Cliente' %><br>
      <%= tag.input type: 'text', name: 'user[fullname]',
      value: 'Jose da Silva', size: 40, id: :userFullName %>
    </h3>

    <h3>
      <%= tag.label 'Email do Cliente' %><br>
      <%= tag.input type: 'text', name: 'user[email]',
          value: 'jose_da_silva@gmail.com', size: 40, id: :userEmail %>
    </h3>

    <h3>
      <%= tag.label 'Data de Nascimento' %><br>
      <%= tag.input type: 'text', name: 'user[birthDate]',
      value: '1997-06-09', size: 10, id: :userBirthDate %>
    </h3>

    <h3>
      <%= tag.label 'CPF' %><br>
      <%= tag.input type: 'text', name: 'user[cpf]',
      value: '12345678910', size: 9, id: :userDocument %>
    </h3>
    <h4>Dados de contato</h4>
    <h3>
      <%= tag.label 'Codigo de Área' %><br>
      <%= tag.input type: 'text', name: 'user[areaCode]',
      value:'54', size: 2, id: :userAreaCode %>
    </h3>
    <h3>
      <%= tag.label 'Numero do telefone' %><br>
      <%= tag.input type: 'text', name: 'user[phoneNumber]',
      value: '992235596', size: 9, id: :userPhoneNumber %>
    </h3>
    <h4>Dados de pagamento: </h4>
    <h3>
      <%= tag.label 'Numero do cartão' %><br>
      <%= tag.input type: 'text', name: 'cc[number]',
      value: '5555666677778884', size: 16, id: :ccNumber %>
    </h3>
    <h3>
      <%= tag.label 'mes' %><br>
      <%= tag.input type: 'text', name: 'cc[expirationMonth]',
      value: '06', size: 2, id: :ccMonth %><br>
      <%= tag.label 'ano' %><br>
      <%= tag.input type: 'text', name: 'cc[expirationYear]',
      value: '22', size: 2, id: :ccYear %>
    </h3>
    <h3>
      <%= tag.label 'ccv' %><br>
      <%= tag.input type: 'text', name: 'cc[cvc]',
      value: '123', size: 3, id: :ccCcv %>
    </h3>

    <p>
      <%= tag.button type: :submit do %>
        Confirma
      <% end %>
    </p>
  </article>

<% end %>